config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { registrations: 'admins/registrations', sessions: 'admins/sessions' }
  root to: 'articles#index' 
  mount Bootsy::Engine => '/bootsy', as: 'bootsy' 
  resources :articles 
  resources :topics
  resources :categories
  resources :charts
  resources :marks
  get '/directory' => 'articles#directory', as: 'directory'
  get '/edit/articles' => 'articles#change', as: 'edit_articles'
  get '/edit/topics' => 'topics#change', as: 'edit_topics'
  get '/edit/categories' => 'categories#change', as: 'edit_categories'
  get '/update_topics' => 'articles#update_topics', as: 'update_topics'
  get '/search' => 'articles#search', as: 'search'
  get '/charts' => 'charts#index', as: 'all_charts'
  get '/my_projects' => 'charts#my_projects', as: 'my_projects'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :category
	has_many :articles

	validates :name, presence: true
	validates :category_id, presence: true
	
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	include TopicsHelper
	
	def new
		@topic = Topic.new
		@categories = Category.all
	end

	def create
		@topic = Topic.new(topic_params)
		if @topic.save
			flash[:success] = "You added the '#{@topic.name}' to the Category '#{@topic.category.name}'."
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@topic = Topic.find(params[:id])
	end

	def update
		@topic = Topic.find(params[:id])
		@topic.update(topic_params)
		if @topic.save
			flash[:success] = "Topic named '#{@topic.name}' updated."
			redirect_to edit_topics_path
		else 
			render 'edit'
		end
	end

	def change
		@topics = Topic.all
	end
end

app/helpers/topics_helper.rb
module TopicsHelper
	def topic_params
		params.require(:topic).permit(:name, :category_id)
	end
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= collection_select(:topic, :category_id, Category.all, :id, :name, :include_blank => "Switch Category...", class: 'form-control') %><br /><br />
	<%= f.label :name, "Topic Name"%>
	<%= f.text_field :name, class: 'form-control' %><br />
	<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/topics/change.html.erb
<div class= "container">
	<div class="row">	
		<div class="col-md-9">
			<h4>List of Topics</h4>
			<% @topics.each do |topic| %>
				<ul class="indentless">
				<li><%= link_to topic.name, edit_topic_path(topic)%></li>
				</ul>
			<% end %>
		</div>
		<div class="col-md-3 pull-right">
		</div>
	</div>
</div>

app/views/topics/edit.html.erb
<h3>Editing topic belonging to: '<%= @topic.category.name %>' category. </h3>

<%= render partial: 'topics/form' %>

app/views/topics/new.html.erb
<%= render partial: 'topics/form' %>