config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { registrations: 'admins/registrations', sessions: 'admins/sessions' }
  root to: 'articles#index' 
  mount Bootsy::Engine => '/bootsy', as: 'bootsy' 
  resources :articles 
  resources :topics
  resources :categories
  resources :charts
  resources :marks
  get '/directory' => 'articles#directory', as: 'directory'
  get '/edit/articles' => 'articles#change', as: 'edit_articles'
  get '/edit/topics' => 'topics#change', as: 'edit_topics'
  get '/edit/categories' => 'categories#change', as: 'edit_categories'
  get '/update_topics' => 'articles#update_topics', as: 'update_topics'
  get '/search' => 'articles#search', as: 'search'
  get '/charts' => 'charts#index', as: 'all_charts'
  get '/my_projects' => 'charts#my_projects', as: 'my_projects'

end

app/models/chart.rb
class Chart < ActiveRecord::Base
  has_many :marks
  validates :title, presence: true
  validates :goal_date, presence: true
  
  attr_reader :chart_creator

  def chart_creator(chart_id)
    chart = Chart.find[chart_id]
    first_name = Admin.find[chart.creator_id].first_name
    last_initial = Admin.find[chart.creator_id].last_name[0]
    "#{first_name} #{last_initial.capitalize}."
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  include ChartsHelper
  def index
    @charts = Chart.all
  end

  def my_projects
    @charts = Chart.where(creator_id: current_admin.id)
  end

  def new
    @chart = Chart.new
  end

  def create
    @chart = Chart.new(chart_params)
    @chart.creator_id = current_admin.id
    if @chart.save
      flash[:success] = "You're off to a great start!"
      redirect_to my_projects_path
    else
      render 'new'
    end
  end

  def show
    @chart = Chart.find(params[:id])
    @mark = Mark.new
  end

  def edit
    @chart = Chart.find(params[:id])
    @mark = Mark.new
  end

end

app/helpers/charts_helper.rb
module ChartsHelper
  def chart_params
    params.require(:chart).permit(:title, :description, :goal_date, :creator_id)
  end
end

app/views/charts/_error_messages.html.erb
<% if @chart.errors.any? %>
  <div id="error">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@chart.errors.count, "error") %>.
    </div>
    <ul>
    <% @chart.errors.full_messages.each do |message| %>
      <li><%= message %>.</li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/charts/_form.html.erb
<div class= "container">
  <div class="row"> 
    <div class="col-md-6">
      <%= form_for @chart do |f| %>
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: "form-control" %><br />
        <%= f.label :description, "Description" %>
        <%= f.text_field :description, class: "form-control" %><br />
        <%= f.label :goal_date %><br />
        <%= f.text_field :goal_date, class: "datepicker col-md-3" %><br />
        <br />
        <%= f.submit "Start!", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/charts/edit.html.erb
<%= render partial: 'marks/form' %>

app/views/charts/index.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<div class= "container">
  <div class="row">
    <div class= "col-md-9">
      <h3>What Everyone's Working On:</h3>
       
        <%= pie_chart Admin.group(:first_name).count %>

     </div>
  </div>
</div>

app/views/charts/my_projects.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<div class= "container">
  <div class="row">
    <div class= "col-md-9">
      <h3>My Current Projects</h3>
      <%= link_to "Start a New Project", new_chart_path %>
      <% @charts.each do |chart| %>
        <ul>
          <li><%=link_to chart.title, edit_chart_path(chart.id)%></li>
        </ul>
          <% if chart.marks.present? %>
            <% chart.marks.each do |mark| %>
            <h4><%=mark.description%></h4>
            <%end%>
          <%end%>
    <% end %>
    </div>
  </div>
</div>

app/views/charts/new.html.erb
<div class= "container">
  <div class="row">
    <div class= "col-md-9">
    <%= render partial: 'error_messages' %>
    <h3>Starting a new project is easy.</h3>
    <p>Get inspired with these <%= link_to "ideas", '#'%> or check out what others are <%= link_to "working on", charts_path%>.</p>
    <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/charts/show.html.erb
<h1>show page for chart</h1>
<%= render partial: 'marks/form' %>