config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { registrations: 'admins/registrations', sessions: 'admins/sessions' }
  root to: 'articles#index' 
  mount Bootsy::Engine => '/bootsy', as: 'bootsy' 
  resources :articles 
  resources :topics
  resources :categories
  resources :charts
  resources :marks
  get '/directory' => 'articles#directory', as: 'directory'
  get '/edit/articles' => 'articles#change', as: 'edit_articles'
  get '/edit/topics' => 'topics#change', as: 'edit_topics'
  get '/edit/categories' => 'categories#change', as: 'edit_categories'
  get '/update_topics' => 'articles#update_topics', as: 'update_topics'
  get '/search' => 'articles#search', as: 'search'
  get '/charts' => 'charts#index', as: 'all_charts'
  get '/my_projects' => 'charts#my_projects', as: 'my_projects'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :topics
  has_many :articles, :through => :topics
	validates :name, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	include CategoriesHelper
		
	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "You created a Category called #{@category.name}"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update(category_params)
		if @category.save
			flash[:success] = "Category named '#{@category.name}' has been updated."
			redirect_to edit_categories_path
		else 
			render 'edit'
		end
		
	end

	def change
		@categories = Category.all
	end

	def destroy
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def category_params
		params.require(:category).permit(:name)
	end
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.label :name, "Category Name"%>
	<%= f.text_field :name, class: 'form-control' %><br />
	<%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/categories/change.html.erb
<div class= "container">
	<div class="row">	
		<div class="col-md-9">
			<h4>List of Categories</h4>
			<% @categories.each do |category| %>
				<ul class="indentless">
				<li><%= link_to category.name, edit_category_path(category)%></li>
				</ul>
			<% end %>
		</div>
		<div class="col-md-3 pull-right">
		</div>
	</div>
</div>	

app/views/categories/edit.html.erb
<h3>Editing this category:</h3>

<%= render partial: 'categories/form' %>

app/views/categories/new.html.erb
<%= render partial: 'categories/form' %>