config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { registrations: 'admins/registrations', sessions: 'admins/sessions' }
  root to: 'articles#index' 
  mount Bootsy::Engine => '/bootsy', as: 'bootsy' 
  resources :articles 
  resources :topics
  resources :categories
  resources :charts
  resources :marks
  get '/directory' => 'articles#directory', as: 'directory'
  get '/edit/articles' => 'articles#change', as: 'edit_articles'
  get '/edit/topics' => 'topics#change', as: 'edit_topics'
  get '/edit/categories' => 'categories#change', as: 'edit_categories'
  get '/update_topics' => 'articles#update_topics', as: 'update_topics'
  get '/search' => 'articles#search', as: 'search'
  get '/charts' => 'charts#index', as: 'all_charts'
  get '/my_projects' => 'charts#my_projects', as: 'my_projects'

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"><small><span class="glyphicon glyphicon-home"></span></small> <%= link_to "Fractured Atlas IKB", root_path%></div>
      </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Directory", directory_path %></li>
        <%= form_tag(search_path, method: :get, id: "search-form", class: "navbar-form navbar-right") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search articles..." %>
          <%= submit_tag "Search", class: "btn btn-default btn-sm" %>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create...<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%=link_to "Article", new_article_path %></li>
            <li><%=link_to "Topic", new_topic_path %></li>
            <li><%=link_to "Category", new_category_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">View/Edit<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%=link_to "Articles", edit_articles_path %></li>
            <li><%=link_to "Topics", edit_topics_path %></li>
            <li><%=link_to "Categories", edit_categories_path %></li>
          </ul>
        </li>
          <li class="dropdown">
           <a href= "#"<class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i><%= "(#{@admin_name})"%></i><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Projects", my_projects_path %>
            <li><%= link_to "All Art Charts", charts_path %>
            <li><%= link_to "Log Out", destroy_admin_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ikb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
  <script>
    $(function() {
      $('.datepicker').datepicker({ dateFormat: 'yy-mm-dd' });
    });
  </script>
</head>
<body class= "link">
	<% if admin_signed_in? %>
	 <%= render 'layouts/nav' %>
  <% end %>

	<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>

</body>
</html>